approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

plugins:
  - checksum: 7465b7797c101aef0745631aa3c78b408f4f2f6b9da02becdec9aa24ab3194bcdaf8249a9e3733693e6c31a2ac242958f5a9ea19f16d04531706939329d8eccf
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: 'https://github.com/cca-io/yarn-plugin-licenses/releases/latest/download/plugin-licenses.js'
